### ISSUE TITLE
Revamp

### ISSUE THREAD

**Issue by shruti170901** [shruti170901/Leetcode#117]
Revamp the names of existing codes to match the followed nomenclature(remove question numbers from beginning, etc. ) and remove non C++ codes if any.

**Comment by vikhyatsingh123** [comment]
Assign it to me. I can do it

**Comment by shruti170901** [comment]
Assigned. Note one thing... Don't remove the  .bash  file

**Comment by vikhyatsingh123** [comment]
@shruti170901 I updated file name and other things.
